---
- name: Install crond, when crond not install on OS.
  yum:
    name: crontabs
    state: present
  tags: logrotate

- name: Start service crond, if not started
  service:
    name: crond
    enabled: yes
    state: started
  tags: logrotate

- name: Install logrotate, when logrotate not install on OS.
  yum:
    name: logrotate
    state: present
  tags: logrotate

- name: Make test directory
  file:
    path: /tmp/log
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: logrotate

- name: Copy test files
  copy:
    src: ./mysqld.log
    dest: /tmp/log/mysqld.log
    mode: '0644'
  tags: logrotate

- name: Replace config file
  copy:
    src: ./mysql
    dest: /etc/logrotate.d/mysql
    owner: root
    group: root
    mode: '0644'
  tags: logrotate
